services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth-ms
    environment:
      - SERVER_DB=db
      - NAME_DB=${NAME_DB-db_auth}
    ports:
      - 8000:8000
    volumes:
      - ./logs:/app/logs
    networks:
      - net-auth
    depends_on:
      - db
  db:
    image: postgres:alpine
    container_name: postgresql
    environment:
      - POSTGRES_USER=${USER_DB-admin}
      - POSTGRES_PASSWORD=${PASSWORD_DB-1234}
    ports:
      - 15433:5432
    networks:
      - net-auth
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
networks:
  net-auth:
    driver: bridge

